CREATE DATABASE wikidb OWNER wiki;
CREATE DATABASE n8ndb OWNER n8n;
CREATE DATABASE ollamadb OWNER ollama;

GRANT ALL PRIVILEGES ON DATABASE wikidb TO wiki;
GRANT ALL PRIVILEGES ON DATABASE n8ndb TO n8n;
GRANT ALL PRIVILEGES ON DATABASE ollamadb TO ollama;
